### PR TITLE
Fix computed property override deprecations

### PR DESCRIPTION
**Pull request by herzzanu**
Handles this https://deprecations.emberjs.com/v3.x/#toc_computed-property-override

### CODE REVIEW

**Comment by arthur5005** [comment]
Can we get this merged? :D!

**Comment by sinankeskin** [comment]
Could you please release a new npm package?

Thank you.

**Comment by Exelord** [comment]
There is a bug that needs to be fixed. whenever options will be set, the getter will omit it and return `{}` always

**Comment by sinankeskin** [comment]
This is really odd because I've implemented this fix to your addon and I've been using successfully. Deprecation messages gone for my case.

**Comment by Exelord** [comment]
Deprecation is gone but new issue is there. I need to find some time to fix it.

**Comment by sinankeskin** [comment]
Yes, I see. You are right.

I guess, you need to set a private variable for options to make non-volatile.

Ok. Thanks.

**Comment by Exelord** [comment]
exaclty

**Comment by rahsheen** [comment]
Any movement on this? Any assistance needed?

**Comment by Exelord** [comment]
Sure, if someone can fix it by using private prop inside getter and setter it would work again :)

**Pull request merged**
