### PR TITLE
Add support for adapter layer

### PR DESCRIPTION
**Pull request by KillaPL**
This is initial work for adapter layer support. This is a work in progress, and I'm sharing it early so that we can align our visions and discuss over some code.

I would like to focus on usage API and the general approach here, I will cleanup and polish the code once we're happy with the behavior.

It supports the following methods in adapters: `methodForModelAction`, `methodForResourceAction`, `headersForModelAction`, `headersForResourceAction`, `urlForResourceAction` and `urlForResourceAction`.

These methods allow user to set up used url, http method and request headers in adapter, for both method and resource actions.

My observations at this point mainly is:

Doing separate methods for method and resource actions feel unnecessary. As I understand it, the only time this is useful is when there is model action and resource action named the same way. This in itself feels like it won't happen often, and if it does, adapter can recognize what situation is this by having or not having snapshot passed in params. If necessary, we can even send "actionType" to adapter as "method" or "resource".

I also think issue raised in #24 will be covered by these new methods.

@Exelord What do you think?

EDIT: Forgive the yarn.lock, I will remove it once the code is ready for merging.

### CODE REVIEW

**Comment by Exelord** [comment]
Hey :)
It looks cool! I will dive into it during the weekend 🏄

**Comment by KillaPL** [comment]
@Exelord Did you have a chance to look at the code? Are you ok with having a single `methodForAction`, `headersForAction`, `urlForAction` ?

**Comment by Exelord** [comment]
Sorry :/
... in my opinion, we should be able to use methods per action... like with find query etc..
eg.
`methodForPublishAction` or `urlForArchiveAction`

otherwise, users would have to think about actions name which should not be the case - ever.

This feature should extend the ability to customize the default adapter methods which are used for url generation.

But I need to think about it one more time. Maybe there is other simpler solution for that. Feel free to share your thoughts.

**Comment by KillaPL** [comment]
This seems like less elegant solution for me, but I am happy to accept your decision. In the end the code ends up in adapters, which is my goal here. If you would, please, confirm your decision, I'll happily change the implementation to work like this.

**Comment by Exelord** [comment]
OK, let's move with the `methodForPublishAction` proposition.
Overall, tests look good but we definitely need to keep the code much simpler and cleaner than it is in the current solution.

So, I propose to go with the following flow:

## 1. `methodFor`
- [ ] **implementation**
We can start with extending `resourceType` property. The function should check if `methodFor***Action` has been defined and if is return it. Otherwise, return `type` from the provided `config`.

- [ ] QA sessions
- [ ] **tests**
We should check if our fallback works correctly.

- [ ] merge to a feature branch

## 2. `headersFor`
- [ ] **implementation**
We need to create a computed property `headers` in `action`. We should also avoid creating a snapshot in two places `action` and `urlBuilder`. Maybe we will need some kind of move to unification or rework of responsibilities.
- [ ] **QA sessions**
In my opinion, there is a lot of work todo to prepare a good architecture for headers as well as for urlFor. I will try to build a proper structure for that. Or maybe we should make some pair programming on that. We definitely can not extend `data` property for that purpose and pass everything to the `urlBuilder`.
- [ ] tests
We have to decide which option will be stronger. I mean, the adapter `headersFor` or `headers` from `ajaxOptions` (in action definition)
We should check if our fallback works correctly.
- [ ] merge to a feature branch

# To be discussed after 1 and 2
___

## 3. `urlFor`
- [ ] implementation
- [ ] QA sessions
- [ ] tests
- [ ] merge to a feature branch

**Comment by Exelord** [comment]
Hi @KillaPL 
How do trigger dummy app to use `dummy/adapters` ? I can not get it resolved and I am wondering if it is not a bug?

**Comment by Exelord** [comment]
Forget it :D 
I forgot to add the need to the unit tests

**Comment by Exelord** [comment]
Closed in favor of #28.
Thanks @KillaPL 😊

**Pull request closed without merging**
